### ISSUE TITLE
Tests to display workflow with typescript

### ISSUE THREAD

**Issue by garkin** [weichx/cerialize#2]
How am i supposed to import `serialize.d.ts` inside my `/typings/tsd.d.ts` to be able to use it inside my Typescript module?
```javascript
import {Serialize, serialize} from 'cerialize';
```

I'm trying it currently as:
```javascript
/// <reference path="../node_modules/cerialize/dist/serialize.d.ts" />
```
And i get an error:
> Error:(1, 35) TS2307: Cannot find module 'cerialize'.

Since `serialize.d.ts` does not contains ambient declaration:
```javascript
export module "cerialize" {  }
```

**Comment by garkin** [comment]
Looks like i need to import it like a typescript file, relative to npm module:
```javascript
import {Serialize,serialize} from 'cerialize/src/serialize';
```

**Comment by weichx** [comment]
Hi garkin, so far the project has expected es6 imports with a relative path.
`import { serialize } from '../node_modules/cerialize/src/serialize'`
that should get you started for now but I'll take a look at getting it to work with tsd definitions

**Comment by weichx** [comment]
I havent had much luck exposing typescript packages to npm, have you seen any good examples I can borrow from?

**Comment by mightea** [comment]
With the new [typings package](https://www.npmjs.com/package/typings) you can import the cerialize typings by running `typings install npm:cerialize` --save and it will use the typings provided with the cerialize npm package

**Comment by weichx** [comment]
very cool, I'll check this out thanks for passing it along
