### ISSUE TITLE
how to install  the library

### ISSUE THREAD

**Issue by hdcos** [weichx/cerialize#23]
Hello there I am pretty new in typescript and javascript and I have big trouble installing your library.
I installed it with npm

    npm install --save cerialize

I have the autocompletion in visual studio code and I find the library on the disk so it seems to work.
But when I load my application I have strange messages

    serialize.js:10 Uncaught ReferenceError: exports is not defined
    angular2-polyfills.js:126 GET http://localhost:3000/cerialize 404 (Not Found)

 and the app is broken.
I added the serialize.js script in the header though.

    <script src="node_modules/es6-shim/es6-shim.min.js"></script>
    <script src="node_modules/systemjs/dist/system-polyfills.js"></script>
    <script src="node_modules/angular2/es6/dev/src/testing/shims_for_IE.js"></script>

    <script src="node_modules/angular2/bundles/angular2-polyfills.js"></script>
    <script src="node_modules/systemjs/dist/system.src.js"></script>
    <script src="node_modules/rxjs/bundles/Rx.js"></script>
    <script src="node_modules/angular2/bundles/angular2.dev.js"></script>
    <script src="node_modules/angular2/bundles/http.dev.js"></script>
    
    <script src="node_modules/angular2/bundles/router.dev.js"></script>
    
    <script src="node_modules/cerialize/dist/serialize.js"></script>
    <script>
      System.config({packages: {app: {format: 'register', defaultExtension: 'js'}}});
      System.import('app/main')
            .then(null, console.error.bind(console));
    </script>
  </head>

Using google chrome. Hope you will help me

**Comment by hdcos** [comment]
note: when I remove the serialize.js script from the head the message
    serialize.js:10 Uncaught ReferenceError: exports is not defined
disapear but still have the others

**Comment by weichx** [comment]
You need to set the "module" key in tsconfig to "commonjs" if it isnt already. thats the source of the 'exports' missing, typescript is trying to compile the files but that variable isnt defined unless "commonjs" is set

**Comment by weichx** [comment]
actually, on closer look, you probably cant use the library via script tag, you'll need to use `require` or `import` to get it into your app

**Comment by hdcos** [comment]
The "module" key in tsconfig is set to "system". I just followed the angular2 tutorial. If I change this value angular2 tells me that require is not defined.

I can't load your library with systemjs?

**Comment by hdcos** [comment]
Ok I have lost too much time trying to import and use this library (not your problem, just lack of experience and knowledge), I will change the architecture of my application instead. Instead of OOP I will use modules and plain javascript object. So computation and data are decoupled and serialization/deserialization not a problem anymore
