### ISSUE TITLE
Cannot load cerialize in angular-cli application

### ISSUE THREAD

**Issue by st-clair-clarke** [weichx/cerialize#24]
Hi,
I have been trying to load cerialize in an angular-cli generated application for the last two days without much success. The semantics of the directory structure are different from the seed I previously used. I have tried various forms of the following without much success

file | angular-cli-build.js

var Angular2App = require('angular-cli/lib/broccoli/angular2-app');

module.exports = function (defaults) {
  return new Angular2App(defaults, {
    vendorNpmFiles: [
      'systemjs/dist/system-polyfills.js',
      'systemjs/dist/system.src.js',
      'zone.js/dist/**/*.+(js|js.map)',
      'es6-shim/es6-shim.js',
      'reflect-metadata/**/*.+(js|js.map)',
      'rxjs/**/*.+(js|js.map)',
      '@angular/**/*.+(js|js.map)',
      '@angular2-material/**/*.js',
      'angularfire2/**/*.js',
      'serialize.js',
      'firebase/lib/*.js',
      'lodash/lodash.js'
    ]
};

file | system-config.ts
const map: any = {
  '@angular2-material': 'vendor/@angular2-material',
  'cerialize': 'vendor/cerialize/dist/serialize.js',
  'lodash': 'vendor/lodash/lodash.js'
};

I cannot seem to find a way to reference the serialize.d.ts.

Thanks for your help.

**Comment by weichx** [comment]
What is your module field set to in tsconfig? I haven't worked at all with the "system" module setting which may be part of the issue here. The d.ts file sits right along side the js file and is setup correctly in the package file's typings field.

I have literally zero experience with angular 2 (Vue is 10x better by the way), is what you're doing the normal way to import dependencies in that frame work?

**Comment by weichx** [comment]
Looked into this a bit more, angular cli is accepting the files and pushing them through a broccoli funnel. Shouldn't serialize.js be nested under cerialize/dist/?

**Comment by weichx** [comment]
closing since I haven't determined that this isn't a setup issue and haven't heard back in a while.
