### ISSUE TITLE
Factories/callbacks for serialization and deserialization

### ISSUE THREAD

**Issue by jfstephe** [weichx/cerialize#25]
Hi,
Thanks for you great work on this library. One problem I have at the moment is that I want to be able to instantiate objects ( new Class() ) from a factory not using the standard object creation. I can also think of scenarios where it would be good to hook into the deserialization step, rather than relying on JSON.stringify.

Any chance you could add these hooks in? I was thinking of passing a function to the decorators for the particular fields, which would optionally be used for object creation or deserialization.

I would create a PR for this but my current employer does not allow contributing to OS projects (go figure!?!!).

Regards,
John

**Comment by weichx** [comment]
Can you provide a sample of the api you are looking for? I don't quite follow what you are asking for but happy to add features if they make sense.

**Comment by jfstephe** [comment]
Thanks for your response. The specific problem we had was with TypeScript enums, being deserialized as strings. So I was thinking of rather than:

export class ParentClass {
@deserializeAs(MyEnumType) someEnumProperty; // deserialised as a string
}

something like (some types added):

// For deserialization
stringToEnum(EnumType: any, value:string) {
  return new EnumType(value);
}
// For serialization
enumToString(value: any) {
  return EnumType[value];
}

export class ParentClass {
@deserializeUsing(MyEnumType, stringToEnum, enumToString) someEnumProperty;
}

// Similarly, this could be extended to the class level (with serialise and deserialise operations split out into different decorators).

export class MyClassFactory {
  createObjectFromString(...) {
  // ... 
  }
  createStringFromObject(....) {
  // ...
  }
}

@deserializeUsing(MyClassFactory.createObjectFromString);
@serializeUsing(MyClassFactory.createStringFromObject);
export class MyClass {
}

I hope that makes sense! What do you think?
J

**Comment by weichx** [comment]
well we already have enums figured out, try using `SerializableEnumeration(enum)` after declaring your enum and then it should work fine.

```javascript
enum Color { Red, Blue, Green}
SerializableEnumeration(Color);

class ThingWithAColor {
    @autoserializeAs(Color) public color : Color;
}

```

To achieve your factory scenario, I think the following would work today.

```javascript
class Vector3 {
@autoserialize public x : number;
@autoserialize public y : number;
@autoserialize public y : number;
}

class Vector3Factory {
    public static CreateFromString(source : string) : Vector3 {
        return Deserialize(source, Vector3);
   }

   public static CreateStringFromObject(obj : Vector3) : string {
       return JSON.stringify(Serialize(obj));
   }

}
```

Does that solve your problem?

**Comment by algreasley** [comment]
belated appreciation for the above  - this works perfectly, thank you)

**Comment by weichx** [comment]
Awesome, glad to hear it
