### ISSUE TITLE
autoserializeAs(Entity) does not deserialized the entity

### ISSUE THREAD

**Issue by klewar2** [weichx/cerialize#28]
I have an entity that contains another entity : 

```javascript
export class SessionEvent {
  @autoserialize id: number;
  title: string;
  editable: boolean;
  @autoserialize product: Product; 
}
```

I have declared functions on the product entity. When i use `@autoserialize`, i have the product object but he is not instanciate, and when i use `@autoserializeAs(Product)` or `@autoserialize(Product, 'product')`, i haven't object or product entity in the return of `Deserialize(json, SessionEvent)`.

Thanks

**Comment by weichx** [comment]
This should work totally fine. Does product have any serialization annotations on any of its properties? If not that could be one explaination.
```typescript
export class SessionEvent {
  @autoserialize id: number;
  title: string;
  editable: boolean;
  @autoserializeAs(Product) product: Product; 
}

export class Product {
   @autoserialize public id : string; //making up a dummy property
}

var evt = Deserialize(json, SessionEvent);
```

**Comment by klewar2** [comment]
Thank for your quick answer.
Below my product entity :

```javascript
import { PricingPolicy } from './pricing-policy';
import { BookingField } from './booking-field';
import { Category } from './category';
import { TaxFee } from "./tax-fee";
import { PricingType, DateType, AvailabilityType, ConfirmBookingsType, ProductType } from './type';
import { autoserialize, autoserializeAs } from 'cerialize';
import * as _ from 'lodash';

export class Product {

  @autoserialize id: number;
  @autoserialize type: string; // ProductType
  @autoserialize name: string;
  @autoserialize sku: string;
  @autoserializeAs(Category) categories: Category[];
  @autoserialize pricingType: string; // PricingType
  @autoserializeAs(PricingPolicy) pricingPolicies: PricingPolicy[];
  @autoserializeAs(TaxFee) taxes: TaxFee[];
  @autoserialize qtyRequired: boolean;
  @autoserialize qtyMin: number;
  @autoserialize qtyMax: number;
  @autoserialize qtyLabelSingular: string;
  @autoserialize qtyLabelPlural: string;
  @autoserialize shortDescription: string;
  @autoserialize longDescription: string;
  @autoserialize images: string[];
  @autoserialize enable: boolean;

[...]

}
```
Below my session event json : 
```json
{
  "data": {
    "id": 1,
    "start": "2016-07-17T12:09:36Z",
    "end": "2016-07-17T15:09:36Z",
    "allDay": false,
    "product": {
      "id": 0,
      "name": "Product 1",
      "sku": "P1"
    }
  }
}

```

I need to do that to make it works : 

```javascript
   let item = Deserialize(res, SessionEvent);
   item.product = DeserializeInto(item.product, Product, new Product());
```

**Comment by weichx** [comment]
one thing that stands out is your json format, do you account for the root node being `data` and not the item properties themselves? `var item = Deserialize(json.data, Item)` for example

**Comment by antitoine** [comment]
Yes (I'm working with @klewar2 ), I can't reproduce the problem in a simple plunker... [available here](http://plnkr.co/edit/eGHEMG?p=preview) 

The real application is more complex and maybe the problem comes from elsewhere...
I will try again soon !

**Comment by antitoine** [comment]
We found the problem.
We use webpack to build the project, and his particularity is that every folder can have a `index.ts` that export all class of the folder (in every files).

When the SessionEvent is deserialized, the Product class is unknown because the Product file is not loaded yet at this time.
We changed the order in the `index.ts` (put Product class before SessionEvent) and this fix the issue. An other option is to import explicitly the class without use the `index.ts`.

Thank for your help !

**Comment by meakyl** [comment]
We had a similar issue in our project.
The order in the index.ts file is important. 

If you have one file with 2 classes, the order in which the classes are written is important too.
This caused some headache in our team :)

Is this a normal behavior ?

Thank you

**Comment by weichx** [comment]
Yes it is normal, circular references won't work. Its a language limitation unfortunately.
