### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by meakyl** [weichx/cerialize#29]
Is there any way to choose the serialized date format ?
I'm using a NoSQL database for storage and I would like the dates to be stored in the string ISO format "2016-07-21T15:54:59.928Z".
When using cerialize, I have something like "Tue Jul 26 2016 09:54:56 GMT+0200 (Romance Daylight Time)"

Thank you

**Comment by nick-jones** [comment]
I believe `OnSerialized` can be used to achieve this.. something along the lines of this..

```TypeScript
class Foo {
    @autoserializeAs(Date) d : Date;

    public static OnSerialized(instance : Foo, json : any) {
        if (instance.d) {
            json.d = instance.d.toISOString();
        }
    }
}
```

The `Date` constructor [accepts `ISO 8601` formatted strings](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Date), so an equivalent for deserialization may not be required.

**Comment by meakyl** [comment]
Yes that's typically something I would like to avoid. Being forced to to this for every date property manually.
I looked at the source code and it's just a .toString(). ISO format is better for me as it is sortable and queryable easier. And JSON.stringify on a Date object gives the ISO format.
Is there a reason why cerialize uses toString() instead of JSON.stringify(..) ?

**Comment by weichx** [comment]
You should be able to provide a custom serialization / deserialization function to `@autoserializeAs`. It would look like this:

```typescript
var CustomDate = {
Serialize: function(date : Date) { return date.toYourFormat(); },
Deserialize: function(json : any) : Date {
       return json.getMyDate();
   }
}

class Thing {
   @autoserializeAs(CustomDate) date : Date;
}
```

the date is toString() because I didn't know about toISOString() 😃  I'll change it soon

**Comment by meakyl** [comment]
It works with you suggestion though I changed it a little.
```
let CustomDate = {
    Serialize: function (date: Date) { return date.toISOString(); },
    Deserialize: function (json: any): Date {
        return new Date(json);
    }
};
```
We can live with this for now but it would be a lot better if we can choose the format or if you decide to use ISO format as default.
thank you.

**Comment by weichx** [comment]
if you upgrade it should work, i changed the format to ISO by default for date serialization

**Comment by meakyl** [comment]
I upraged and it works perfectly thanks

**Comment by weichx** [comment]
awesome, glad to hear it
