### ISSUE TITLE
autoserializeAs('key') does not work with private attribute

### ISSUE THREAD

**Issue by antitoine** [weichx/cerialize#30]
Hi,

I can't change the key name of a private attribute or public.
I reproduce the problem in this plnkr : http://plnkr.co/edit/ncZp38

In every configuration that I tried, the key name is unchanged.

Someone has any clue on this issue ?

Thanks by advance

**Comment by antitoine** [comment]
Sorry, I forgot to use Serialize function to get the json ...
So, this solve the problem : 
```javascript
JSON.stringify(Serialize(this.product))
```
the plnkr solved : http://plnkr.co/edit/iDtNaF

**Comment by weichx** [comment]
So you're all set? Should I close this?

**Comment by antitoine** [comment]
Yes, all good ! Thank you

**Comment by weichx** [comment]
great
