### ISSUE TITLE
 @xxxIndexable annotations don't support ES6 Maps

### ISSUE THREAD

**Issue by christophercr** [weichx/cerialize#32]
Currently, the @ @xxxIndexable annotations allow the user to work with simple objects to be used as a dictionary in the way {[idx : string] : SomeClass} , which is basically what the Maps in ES6 are. However, such Maps are not yet supported by these annotations.

Is it possible to have ES6 Maps supported?

**Comment by weichx** [comment]
I see what you're getting at but I'm not sure it would work. Feel free to argue with me though. I think the issue there is that json won't support anything other than strings for keys. With a map you likely don't have string keys which is a problem. Also your backend almost certainly can't handle objects as keys even if it were possible.

If you really need to handle serializing a map and have a compelling use case example I'm happy to try and find a way to make it work.

**Comment by christophercr** [comment]
Indeed, as you mentioned, Maps can have objects as keys. My concern what about Maps having an string key though. In that specific case they are basically the same as the dictionary objects currently supported by @xxxIndexable.

In order to get it to work, I had to manually create the map in the OnDeserialized callback and extract the array of values in the OnSerialized callback as follows:

```
public static OnDeserialized(instance:SomeClass, json:any):void {
	let items:Item[] = json.items;
	instance.items = new Map<string,Item>();
	for (let item of items) {
		instance.items.set(item.name, item);
	}
}

public static OnSerialized(instance:SomeClass, json:any):void {
	json.items= Array.from(instance.items.values());
}
```

Obviously, having an array in the JSON is not really what a JS Map should look like, but it is just a simple temporary solution for my needs. In fact, they should be defined as in your current implementation:

```
var json = {
leafMap: { type1: { some leaf data }, type2: { some leaf data } }
};

```

**Comment by weichx** [comment]
I think a nicer way to solve this is to define a custom serialization type. I don't think the edge case of a map having only string keys is something the library should enforce. For your case, heres what I'd suggest:

```typescript
   
   const StringMap = {
    Serialize: (map : Map<string, any>) => {
        var obj = {};
        //I may have the params here backwards
        map.forEach(function (key : string, value: any) {
            obj[key] = Serialize(value);
        });
        return obj;
    },

    Deserialize(json : any) => {
        var map = new Map<string, any>();
        Object.keys(json).forEach(function(key : string) {
            map.set(key, json[key]);
        }
        return map;
    }
}

class YourClass {
    @autoserialize(StringMap) myMap : Map<string, thing>();
}

that way you only define the custom behavior once and don't need to think about it for every object type that uses this string-key'd map type

**Comment by weichx** [comment]
Do you have more thoughts on this? I'd like to close the issue if you dont

**Comment by christophercr** [comment]
Yes, indeed, that is a better solution and more generic for these edge cases. I've tried it out and it worked. Thanks for your support.

**Comment by weichx** [comment]
Awesome (sorry for the crap untested code 😄 ) I'm going to close this but feel free to open another if you have any problems
