### ISSUE TITLE
Deserializing a Map<string, MyClass> with custom serialization type doesn't instantiate the class

### ISSUE THREAD

**Issue by christophercr** [weichx/cerialize#33]
Hi, in fact this issue is related to https://github.com/weichx/cerialize/issues/32. As you suggested, I can use a custom serialization type instead of defining the OnSerialize  and Ondeserialize callbacks everytime. However, the actual class to be instantiated and set into the Map is lost, I now get a `Map<string, Object>`.

Do you know how can I get my actual class to be correctly instantiated?

Probably my first approach (to define the callbacks everytime) may be the only solution by now, but reusing your idea just for the serialization part, for the deserialization I would need to do it in the callback. Something like this:

```javascript
// on my class
class MyClass {
    @serializeAs(StringMap)   // just for serialization
    myMap : Map<string, AnotherClass>();
}

// custom deserialization to get the correct instance of the class
// to be added in every class containing a Map<string, AnyClass>
public static OnDeserialized(instance:MyClass, json:any):void {
    let items:Object = json.items;
    instance.items = new Map<string, AnyClass>();
   Object.keys(items).forEach((key:string) => {
	let instantiatedItem:AnyClass= Deserialize(items[key], AnyClass);
	instance.items.set(key, instantiatedItem);
   });
}

// generic custom serialization type
const StringMap:Object = {
    Serialize: (map:Map<string, any>):any => {
        let obj:Object = {};
        map.forEach((value:any, key:string) => {
            obj[key] = Serialize(value);
        });
        return obj;
    }
};
```

**Comment by weichx** [comment]
What do you mean the class is lost? The type for it or the actual instance?

**Comment by christophercr** [comment]
Sorry, I meant that the type is lost. There is no actual instance, just an object, which makes sense because there is no class provided to the @autoserialize annotation.

**Comment by weichx** [comment]
Oh I see what you mean. If the items in the map are all the same class this is easy, if not you'll have to get creative. I'll circle back in a bit with some options, not at my computer right now.

**Comment by christophercr** [comment]
Well, to clarify: all the elements in the map have the same class, the actual problem is that I can have a map of ClassA, another one of ClassB, and so on... in this case, the deserialization needs to be aware of the right class to instantiate. Basically all boils down to the Deserialize() method, it needs the type to be instantiated.

**Comment by weichx** [comment]
try this:

```typescript
const StringMap = function(targetType : ClassType) {
    return {
      Deserialize: function(json : any) => any {
         let map:Map<string, any> = new Map<string, any>();
        Object.keys(json).forEach((key:string) => {
            map.set(key, Deserialize(json[key], targetType);
        });
        return map;
      }
    };
  }
}


class Thing {
  @autoserializeAs(StringMap(ClassType)) public strMap: Map<string, ClassType>;
}

**Comment by christophercr** [comment]
Indeed, that made the trick. Thanks a lot.

**Comment by weichx** [comment]
No problem, reach out if anything else comes up
