### ISSUE TITLE
Cannot deserialize correctly typed arrays

### ISSUE THREAD

**Issue by BUONJG** [weichx/cerialize#36]
I have issue on array deserialize when I use the following annotation:
```
class Test {
    @deserializeAs(String) public arrayOfString: Array<string>;
    @deserializeAs(Number) public arrayOfNumber: Array<number>;
}
var json = {
  arrayOfString: ['String1', 'String2'],
  arrayOfNumber: [1, 2]
}
var test = Deserialize(json, Test);
```
I get:
'String1,String2' in test.arrayOfString when I expected ['String1', 'String2']
NaN in test.arrayOfNumber when I expected [1, 2]

When I use the following annotation, it works fine:

```
class Test {
    @deserialize public arrayOfString: Array<string>;
    @deserialize public arrayOfNumber: Array<number>;
}
```
The reason why I use deserializeAs instead of deserialize is to make your library take care to the type conversion.

Is there a way I can use your library to manage this?

Regards,

**Comment by BUONJG** [comment]
Just for information, I check in the library, it seems that you can fix this issue adapting deserializeObject function:

do the if (Array.isArray(source)) in first position instead of second position:

if (Array.isArray(source)) {
         instance[keyName] = deserializeArray(source, metadata.deserializedType || null);
} else if (metadata.deserializedType && typeof metadata.deserializedType.Deserialize === "function") {
         instance[keyName] = metadata.deserializedType.Deserialize(source);
}

I don't know what will be the impact on the behavior of cerialize in other cases.

Please keep me informed if the solution is correct and can be integrated in a next version of cerialize.

Regards,

**Comment by weichx** [comment]
As far as I can tell the library is doing the right thing. We don't want to do the array check first because we need to prioritize custom deserializers. As a rule you shouldn't be use `xxxxAs` annotations on primitive data unless you need to change the key or want custom behavior. I'm not sure I understand what you mean by having the library take care of the type conversion. Can you elaborate?

**Comment by BUONJG** [comment]
The issue we have is if we do not specify @deserializeAs(String), if the data doesn't contain a String but a Number, we will not have a string in the object created by Cerialize but a Number.

Specifying @deserializeAs(String), Cerialize will convert the number into a string, it is what we expect.

But in the case of an array of string, the array is converted into a string not into an array of string.

**Comment by weichx** [comment]
So you are trying to cast a number to a string when deserializing? (or vice versa)

**Comment by BUONJG** [comment]
Hello,

We have the case yes (cast string into number).

We are converting XML message to json and then json to object with
cerialize.

The XML do not contains schema so number are strings in the json and
cerialize is not casting the string into number if we do not sepcify:
autoserializeAs(Number).






2016-10-06 13:08 GMT+02:00 weichx <notifications@github.com>:

**Comment by weichx** [comment]
Got it, so I think this particular use case isn't ideal to provide as built in functionality. What you can do is write a string array to number array (or vice versa) function and pass that in to `deserializeAs` Here is an example: 

```typescript

function StringConverter(array : string[]) : number[] {
    return array.map((item) => { return parseInt(item) } );
}

 function NumberConverter(array : number[]) : string[] {
      return array.map((item) => { return item.toString() });
 }

 class Test {
     @deserializeAs(StringConverter) public arrayOfString: Array<string>;
     @deserializeAs(NumberConverter) public arrayOfNumber: Array<number>;
 }


```

**Comment by weichx** [comment]
@BUONJG does that help you?

**Comment by BUONJG** [comment]
Hello,

Sorry for my late response.

It helps but it is not satisfactory for me.

We are using cerialize each time we have to convert a json to a typed object.

The json data has various origins (XML files, No SQL data storage, web forms data, http request body, query parameters....)

In many case, the can't ensure that the json properties are set with the correct type.

We can make Cerialize help a lot here always specifying @deserializeAs( xxx ) event if xxx if String, Number or Boolean.

It works fine when property is not an array of value types.

But when it is an array, the behavior is not correct (Array of string is converted to a string where array value are concatenated)

As I told you, we fixed this on your library making the check source is an array in first place but I understand it has an impact on other behaviors of the library (we don't use)

But I believe String, Number, Boolean should be manage as any other object types for instance in your documentation regarding dates the usage is:
```
class Test {
     @deserializeAs(Date) public singleDate: Date;
     @deserializeAs(Date) public arrayOfDates: Array<Date>;
 }
```

why not the same usage for String, Number and Boolean?

Regards,

**Comment by weichx** [comment]
I see your point, they should respect the given type if provided explicitly. I'll handle this soon

**Comment by BUONJG** [comment]
Thank you very much.

Have a good day.

2016-10-12 11:40 GMT+02:00 weichx <notifications@github.com>:

**Comment by weichx** [comment]
this should be working now, at least for deserializing
