### ISSUE TITLE
Issue on deserializeAs(String)

### ISSUE THREAD

**Issue by BUONJG** [weichx/cerialize#37]
Hello,

I found another issue using autoserializeAs(String):
```
class SerializeTestClass extends SerializeTestClassBase {
    @autoserializeAs(String) public scalarString: string;
}

json = {
      scalarString: null
}
object = GenericDeserialize<SerializeTestClass>(json, SerializeTestClass);
```

then it results object.scalarString = 'null' (a string with null inside instead of null)

To resolve this in the libary, you only have to add in function deserializeObject
```
if (source === null) {
            instance[keyName] = source;
}
```

Do you want me to do a pull request?

Thank you.

**Comment by weichx** [comment]
Thanks for letting me know, I'm not near my computer right now but I'll
check on this later today

**Comment by BUONJG** [comment]
Hello,

It seems you included this in your last commit.

Thank you very much! :-)

**Comment by weichx** [comment]
no problem, closing this out :)
