### ISSUE TITLE
Issue on deserializeAs(Date) when Date is overwritten

### ISSUE THREAD

**Issue by BUONJG** [weichx/cerialize#38]
Hello,

We are using sinon in our tests to fake dates.
Then, when we use cerialize to convert a json containing a string date, it doesn't return a Date object:

```
let fakeTimers = sinon.useFakeTimers();

class SerializeTestClass extends SerializeTestClassBase {
    @autoserializeAs(Date) public scalarDate: Date;
}
json = {
      scalarDate: (new Date(2016, 0, 1)).toISOString()
}
object = GenericDeserialize<SerializeTestClass>(json, SerializeTestClass);

```

then, object.scalarDate is not a Date instance as expected.

To resolve this you only have to change the way you detect the type corresponds to a date:

metadata.deserializedType === Date 
should be 
metadata.deserializedType === Date.prototype.constructor
(you have this 3 times)

Also:
type === Date
should be
type === Date.prototype.constructor
(you have this only once)

Again, if you want I do a pull request, feel free to ask me.

**Comment by weichx** [comment]
It would be great if you could do a PR for this, thanks!

**Comment by BUONJG** [comment]
Hello,

It seems to me I don't have the permission to create a pull request.

Can you grant me the access?

Regards,

**Comment by weichx** [comment]
closing, merged your pr
