### ISSUE TITLE
Deserialize circular referenced classes

### ISSUE THREAD

**Issue by yuanfeiz** [weichx/cerialize#39]
Suppose there are two classes: `Post` and `Comment`.

```typescript
class Post {
  @autoserialize
  id: string;

  @deserializeAs(Comment)
  comments: Comment[];
}

class Comment {
  @autoserialize
  id: string;

  @deserializeAs(Post)
  post: Post;
}
```

When deserialize a post with comments, it failed to deserialize the `comments`:

*Input*:
```json
{
  "id": "foo",
  "comments": [
    {
      "id": "comment-1"
    }
  ]
}
```

*Output*:
```typescript
let post = Deserialize(json, Post);
expect(post.comments).not.toBeUndefined() // failed!
```

This implementation might seems odd, but I suppose it's a valid use case to have bidirectional association that I can lookup the relevant objects from either side. 

* Is there any limitation on the deserializer?
* Is there a way to implement the association? 

Thanks!

**Comment by weichx** [comment]
Two issues here. The first has to do with Javascript not having a lookahead compiler. At parse time, either Post or Comment won't have been parsed yet and will be undefined, whichever is parsed first, the other won't exist. The second part is a circular reference problem. I certainly see the benefit of having bidirectional pointers here but if you step back and think about how the data would be serialized you'll realize that it can't really work that way. What you can do is sticht up the references post deserialization. Here is an example:

```typescript
class Post {
  @autoserialize
  id: string;

  @deserializeAs(Comment)
  comments: Comment[];

  public static OnDeserialized(instance : Post, json : any) : any {
      instance.comments.forEach(function(comment : Comment) {
      comment.post = instance;
  });
}

class Comment {
  @autoserialize
  id: string;
//note: Not deserialized through an annotation!
  post: Post;
}
```

Does that make sense?

**Comment by yuanfeiz** [comment]
That makes sense! Regarding the second part, suppose the json objects are fetched from two different endpoints: 

```
GET /posts/1

// Response
{
   id: 1,
   comments: [
     {
        id: 42
     }
   ]
}


GET /comments/42

// Response
{
   id: 42,
  post: {
    id: 1
  }
}
```
The API response has made sure that there is not circular reference in one object, though I might need to deserialize the post and comment in different places. Put it in another way: I might sometimes need to deserialize comment, sometimes need to deserialize post, with the API response properly populates the information according to the class definitions. How about this kind of scenario?

**Comment by weichx** [comment]
This isn't something i think this library should handle but I can see why might ask about it. Probably the right move here is to use client side caching and do a second http call to get whichever one you dont have. You can keep a local index by id. If you have two sources of data and need to aggregate them its a good idea to leave that to an abstraction and let the library do what it is built to do.

**Comment by yuanfeiz** [comment]
Ok, thanks anyway. 

BTW, thank you for the great library. It has been the foundation of a large Angular2 app I am working on and serves the purpose of serialization well.

**Comment by weichx** [comment]
I'm glad you're getting some good use out of it, thats great to hear thanks!
