### ISSUE TITLE
Deserialize array of various types

### ISSUE THREAD

**Issue by martinnovak** [weichx/cerialize#42]
Hello, I have a problem with deserializing array of various types. This seems not to be supported, and it would be very helpful as it would enable me to use type hierarchy in serialization.

Example:

``` typescript
enum Type {
  B, C
}
abstract class A
{
  @autoserialize
  type: Type;
}

@inheritSerialization(A)
class B extends A
{
  @autoserialize
  str = "Hello";
}

@inheritSerialization(A)
class C extends A
{
  @autoserialize
  num = 1;
}

class X
{
  @autoserializeAs(() => [B, C])
  array = [ new B(), new C() ];
}

    console.log('=========>>> TEST START <<<==============');
    let x = new X();
    (<B> x.array[0]).type = Type.B;
    (<B> x.array[0]).str = 'LALA';
    (<C> x.array[1]).num = 123;
    (<C> x.array[1]).type = Type.C;
    let json = Serialize(x);
    console.log(json);
    let array2 = Deserialize(json, X);
    console.log(array2);
    console.log('=========>>> TEST END <<<==============');

```

This is just an example of what I'm trying to achieve. My point is to distinguish the type of each object in the array X.array to have different types in deserialization. So, in this example, array2.array[0] would be of type B, and array2.array[1] would be instance of class C.

Maybe you can advise some other solution, I was just playing with autoserializeAs annotation, but I was not able to find out any. Also, please note that in reality, I would like to use it to deserialize a tree with various subnodes, so the depth of the objects can be quite big.

Thank you

**Comment by weichx** [comment]
In general the library is built to handle deserializing a set of data where the types are known at build time. In your case this isn't true because (I assume) the tree nodes are dynamic. One thing to try would be this:

```typescript
abstract class Node {

    public children : Array<Node>;

    public static OnDeserialize(instance : Node, json : any) : void  {
        for(var i = 0; i < json.children.length; i++) {
            const node = json.children[i];
            switch(node.type) {
                case 'NodeA': //this sucks but is a limitation of the language
                    instance.children.push(Deserialize(node, NodeA))
                    break;
                ... etc
            }
        }
    }

}

```

you would probably have to implement OnDeserialize for all node types like this, i don't think static functions are inherited.

**Comment by martinnovak** [comment]
Thank you, this worked well. As you wrote, I created OnDeserialize function (also OnSerialize but for other reason) in all nodes I needed, and I didn't encounter any problem with such access.

**Comment by weichx** [comment]
Awesome, glad to hear it

**Comment by lengtche** [comment]
For those copy pasting example provided by @weichx, function name should read `OnDeserialized`.

Threw me for a bit of a loop.

**Comment by Vaevictus** [comment]
I just ran into this issue. Array returned from server with mixed bag of items that all inherit a common base type.
Feature request here if the language supports it: Could not an attribute be used on the base/abstract type, declaring known subtypes and the associated string value in a specific field as a discriminator?

**Comment by weichx** [comment]
I think this is better handled in an OnDeserialized callback on the base type. Figuring out subtype based on string values feels pretty flimsy to me to be a feature.

**Comment by SirGordon** [comment]
https://github.com/JohnWeisz/TypedJSON
these guys have abstract class deserialization feature, but ofcourse you have to provide some hints.
