### ISSUE TITLE
custom deserialize function

### ISSUE THREAD

**Issue by X4V1** [weichx/cerialize#44]
Hi,

I'm using your library to automatically serialize and deserialize objects retrieved from back-end, and I would like to execute custom treatment before assigning the final value to the property. Is it possible to pass a function to do that ? For example, converting millisecond timestamp to second timestamp, or calculate other things with the received values.

I would like to pass a function to the decorator to be executed before the final assignation. Is-it possible ?

Thanking you in advance.

**Comment by weichx** [comment]
Yup, real easy, dumb example: 

```typescript
const MyConverter = {
            Serialize(input : number){
                return (number * 10).toString();
            },
            Deserialize(json : any, instance?: any)  {
                return parseFloat(json) / 10;
            }
        };

        class TestClass {
            @autoserializeAs(Serializer) timestamp: number;
        }
 Serialize(new TestClass()) //yay
```

**Comment by X4V1** [comment]
Thank you for that information, it works like a charm :+1:
