### ISSUE TITLE
"autoserializeAs" not work.

### ISSUE THREAD

**Issue by stanleytakamatsu** [weichx/cerialize#46]
Assuming I have a "Model" folder with a following structure:
```
Test.Model
-- TestModel.ts
-- TestSubModel.ts
-- Index.ts
```

```
// Test.Model/TestSubModel.ts

export class TestSubModel 
{
   @autoserialize
    private test: string;
}
```

`index.ts` contain:
```
export * from "./TestModel";
export * from "./TestSubModel";
```

```
Another.Test.Model
- AnotherTestModel.ts
- Index.ts
```
There is an inconsistency in functioning in the following scenarios:
```
// Another.Test.Model/AnotherTestModel.ts

export class AnotherTestModel 
{
   @autoserializeAs(TestSubModel)
    private test: TestSubModel;
}
```
When use:

`import { TestSubModel } from "../Test.Model";`  The `autoserializeAs` not work.

`import { TestSubModel } from "../Test.Model/TestSubModel"; ` The `autoserializeAs` works.

I tried to find the problem but could not identify.

**Comment by stanleytakamatsu** [comment]
Note:
```
// Another.Test.Model/AnotherTestModel.ts

import { TestSubModel } from "../Test.Model";

export class AnotherTestModel 
{
   @autoserializeAs("work")
   private _work: string; // The autoserializeAs works.

   @autoserializeAs(TestSubModel)
    private test: TestSubModel; // The autoserializeAs not work.
}
```

**Comment by davidwalschots** [comment]
Most likely, at runtime the reference to TestSubModel doesn't exist yet (TestSubModel is undefined). If you export TestSubModel before TestModel it ought to work. I'd recommend directly referencing from TestSubModel to "../Test.Model/TestSubModel".

**Comment by stanleytakamatsu** [comment]
I added the `debugger` inside the` autoserializeAs`. It clearly shows that the `TestSubModel` class has been loaded and is not as` undefined`.
Anyway, I'll reference the file directly for now.
Thank you very much for the clarification.
