### ISSUE TITLE
lodash dependency 

### ISSUE THREAD

**Issue by rightisleft** [weichx/cerialize#47]
/Users/jmurphy/projects/ubq/api/node_modules/@types/lodash/index.d.ts
Error:(19449, 15) TS2428:All declarations of 'WeakMap' must have identical type parameters.

I'm fairly confident this is a lodash issue, but it was brought in as a dependency of cerialize.

Any advice?

**Comment by weichx** [comment]
Cerialize definitely doesn't have a lodash dependency, it could be a type
resolution conflict, previous versions of typescript didn't include
definitions for es6 collections. I'm not home to check now but I may have
declared a weak map interface which might explain your issue

**Comment by weichx** [comment]
if you get the latest version this should be resolved
