### ISSUE TITLE
Generics Support?

### ISSUE THREAD

**Issue by rightisleft** [weichx/cerialize#49]
Is there a way to work with `DeserializeInto` using a an Abstract Class with a Generic T:

export class BaseService<T> {
 ...
 .map((response) => DeserializeInto(response.json(), T);
}

I understand Typescript discards Types at runtime, which makes this non trivial. Any best practices?

**Comment by weichx** [comment]
Short of typescript reflection (which I'm working on by the way!) I'm not sure it would be possible

**Comment by rightisleft** [comment]
Ya im looking over the reflect-metadata library. I wrote a binder like this in Dart using its Transformer / reflection libraries, but they have a pre processing pipeline at compile time that generates the meta info.

**Comment by weichx** [comment]
yeah you can't do it without pre processing
