### ISSUE TITLE
Is it possible for cerialize to work within es5 environment?

### ISSUE THREAD

**Issue by SirGordon** [weichx/cerialize#51]
Hello!
I have a project that needs a deserializing library for web client, so my question if it's possible to transpile it all to es5 and expect it to be working?
Thanks!

**Comment by weichx** [comment]
Yes target es5 in tsconfig.json, should be fine

**Comment by SirGordon** [comment]
But in the Readme, the last Requirements section states:
"Cerialize uses the ES6 Map implementation so you must be on a browser that supports it or include a shim."
As far as I know, Map cannot be transpiled to es5

**Comment by weichx** [comment]
Depends on your browser target, if you need to target a browser that doesn't support the map, you can add a polyfill for it https://www.npmjs.com/package/es6-map
