### ISSUE TITLE
Nested object Serialization with custom key name

### ISSUE THREAD

**Issue by alejandrocoding** [weichx/cerialize#59]
Hi there,

First things first, thanks for this lib, it's really great.

I am facing a problem , did not see the same error already reported, so I am not sure either it's a new bug, known bug or my mistake but I've attached here below:

When nesting objects, they get mapped with values, that's working fine, but it doesn't get inferred the new name for the property.

The code:

    class Person {
    ....
    @autoserializeAs(Person, 'Girl_Friend')
    public girlFriend: Person;

![image](https://user-images.githubusercontent.com/5755545/26884749-79d0a6ba-4b98-11e7-9204-a89c51e44a06.png)

As you can see in the image attached, the first time girlfriend is serialized, it does work, but not in cascade. And not just the that property but the whole object pending of it, so "Created" at the first level got serialized successfully but not in cascade.

I have tried to declared the OnSerialized method within the Person class to call Serialize method recursivly, but it seems to do not affect it, it just gets hit once.

```
public static OnSerialized(instance: Person, json: any): void {
        if (instance.girlFriend) {
            instance.girlFriend = Serialize(json.Girl_Friend, Person);
        }
    }
```

Thanks in advance :)

**Comment by hyndsite** [comment]
@ialex90 did you get any further with this? I am considering this library - but if what appears to be crucial functionality issues are not responded to in over a week, might be the right lib for my project.

**Comment by ialex90** [comment]
ey @hyndsite, I didn't get further with it and didn't get any response neither yet :( It's sad as the implementation seems very cool and clean

**Comment by connormlewis** [comment]
I believe I'm running into the same issue. Though it's not exactly the same as your case. I'm trying to do something like this:
`class A {
    @autoserializeAs(B) b: B;
}

class B {
    @autoserializeAs(A) a: A;
}`

I looked through the serialize source a bit and after some debugging, it seems that the issue is that at the time it tries to figure out the mapping for A, it doesn't know how to deserialize B, because it hasn't analyzed it yet.

**Comment by briosheje** [comment]
Having a significantly similar issue with a "slightly" more complex problem, it looks like that `autoserialize` is not creating a new instance of a class, but rather a single object not instance of the said class.

Example: I have a nested array with "children" repeating over time, like:

```
[{
   children: [{
       children:[{

        }]
   }]
}]
```

the "children" object is meant to be an instance of a class called `RemoteFileOrFolder`. In my case, the said class is like this:

```
export class RemoteFolderOrFile implements IFolderOrFile {
    @autoserialize public children: Array<RemoteFolderOrFile>;

     // constructor and some custom methods.
};
```

Using autoserialize as above is creating only the nested properties, but the object created is not an instance of the above class.

Using autoserializeAs seems to be doing nothing at all (not even recognizing children), so it really looks like that the compiler doesn't yet know what RemoteFileOrFolder is while deserializing.

**Comment by Diademe** [comment]
I have a similar issue: 
The following code throws an unhandled exception
```typescript
import { Deserialize, autoserializeAs, autoserialize } from 'cerialize';
class Dog  {
    //@autoserialize public species: string;
    @autoserializeAs(Dog) public Friend: Dog;
}
var json = {
    Friend: {
        Friend: null
    }
};
let o = Deserialize(json, Dog);
```
but if I uncomment the `@autoserialize public species:` string, everything is fine. However, if I swap the two autoserialize, I get the exception back
It might solve @briosheje 's problem: add an autoserialize in the top of the class.
