### ISSUE TITLE
Deserialize bad in Union Types

### ISSUE THREAD

**Issue by miao17game** [weichx/cerialize#67]
@deserializeAs(ParameterValue | GetResponseValue)
it doesn't work anyway.

how can i deserialise str to the union type instance?

**Comment by miao17game** [comment]
There is no problem in serialization mode when the type is union.

the union type is not a kind of 'string|Function|Iserializable' .

**Comment by weichx** [comment]
You'll have to implement a custom deserializer for your type. We are only
able to deserialize from concrete type references, unions are a typescript
feature that don't exist at runtime.

**Comment by miao17game** [comment]
well, I know, thanks!!!
