### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by rLoka** [weichx/cerialize#69]
It seems to me that the library can not handle circular objects which is why I get "Maximum call stack size exceeded" upon serialization. Would be great if you could add support for that.

Check https://github.com/WebReflection/circular-json

**Comment by weichx** [comment]
I think this is outside the parameters of the library, if you need circular
references you can set them up via callbacks

Am 29.08.2017 3:54 nachm. schrieb "rLoka" <notifications@github.com>:
