### ISSUE TITLE
Cerialize broken with Typescript 2.4+

### ISSUE THREAD

**Issue by christophercr** [weichx/cerialize#70]
Hi there,

I've been using Cerialize for quite some time and I must say it works like a charm ;)

I have a problem though, I tried to upgrade my project to Typescript2.4 and now I get some TSC errors in the usage of @serialize, @serializeAs and @autoserializeAs annotations:

> Error:(13, 18) TS2345:Argument of type 'typeof MyClass' is not assignable to parameter of type 'string | ISerializable | Serializer'.
  Type 'typeof MyClass' is not assignable to type 'Serializer'.
    Type 'typeof MyClass' provides no match for the signature '(value: any): any'.

and I've seen that for the @serializeIndexable also fails:

> Error:(201, 33) TS2345:Argument of type 'typeof MySerializableObj' is not assignable to parameter of type 'ISerializable | Serializer'.
  Type 'typeof MySerializableObj' is not assignable to type 'Serializer'.
    Type 'typeof MySerializableObj' provides no match for the signature '(value: any): any'.

So this error happens with any class and even with enums as described in #61 

So I guess the Cerialize typings should be adapted since there are [stricter checks in TS 2.4](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#typescript-24).

Do you have an idea how this can be improved?

**Comment by weichx** [comment]
Glad you like the project! I know about the stricter checks in 2.4 but I haven't gotten around to updating this yet unfortunately. We certainly need to update the signatures of the annotations, probably to include something like `INewable<T>` where that would be defined as

````typescript
interface INewable<T> {
new() : T
}
````
