### ISSUE TITLE
Deserialize doesn't work on extended classes.

### ISSUE THREAD

**Issue by briosheje** [weichx/cerialize#75]
Considering this example:

```
class A {
    @autoserialize public test: string;
}

class B extends A {
    @autoserialize public hello: number;
}

let res = Deserialize({test: '123', hello: 1}, B);
```

res will only hold the "hello" property, test will be completely ignored.

Is there any workaround for this?

--- EDIT ---

Nevermind, I've found a workaround, despite it may not work for any case but hey, it's still a fix:

```
class A {
    @autoserialize public test: string;
}

class B extends A {
    @autoserialize public hello: number;

public static OnDeserialized(instance : B, json : any) : void {
    console.log("attempting a desperate fix..!");
    let InnerDeserialization = Deserialize(json, A);
    Object.keys(InnerDeserialization).forEach((k) => {
      !instance[k] && (() => {
        instance[k] = InnerDeserialization[k];
      })();
    });
  }
}

let res = Deserialize({test: '123', hello: 1}, B);
```

Using `OnDeserialized` will ensure that all the properties extracted from the A instance will be set on B as well, if they don't exists already.

**Comment by weichx** [comment]
There's a section in the readme about this, its not inherited by design but you can opt in with a decorator

```
import { inheritSerialization } from 'cerialize';

@inheritSerialization(User)
class Admin extends User {

}
```

**Comment by briosheje** [comment]
@weichx 

Sorry, I didn't notice it at first.

Thanks!
