### ISSUE TITLE
Request: Option to use Object.create instead of new.

### ISSUE THREAD

**Issue by TheBinaryFox** [weichx/cerialize#79]
Would it be possible to add an option that makes cerialize create objects without invoking their constructors? The current implementation of `new (type as any)()` causes issues for objects which freeze themselves in the constructor.

```typescript
import {autoserializeAs, Serialize, Deserialize} from 'cerialize'; // v2

class Immutable {

	@autoserializeAs(String)
	public readonly text: string;

	public constructor(text: string) {
		this.text = text;
		Object.freeze(this);
	}

}

// Demonstration:
let obj = new Immutable('Demo');
let json = Serialize(obj, Immutable);
let obj2 = Deserialize(json, Immutable); // TypeError: Cannot assign to read only property 'text' of object '#<Immutable>'
```

**Comment by weichx** [comment]
This is a version 2 feature already. I haven't released it yet but you can
checkout the https://github.com/weichx/cerialize/tree/mw/v2 branch. Happy to take feedback

Am 06.02.2018 1:33 vorm. schrieb "The Binary Fox" <notifications@github.com

**Comment by TheBinaryFox** [comment]
Thanks for the quick reply! I just looked through the deserialization code, but the closest thing that I found was the option to deserialize into a plain object:

```typescript
else if (createInstances) {
    return new (type as any)();
}
else {
    return {} as T;
}
```

While that definitely works, it won't inherit the prototype chain of the associated type. Unfortunately, that means class methods won't be defined on the deserialized objects:

```typescript
import {autoserializeAs, Serialize, Deserialize} from 'cerialize'; // v2

class Immutable {

	@autoserializeAs(String)
	public readonly text: string;

	public constructor(text: string) {
		this.text = text;
		Object.freeze(this);
	}

	public getUppercaseText() {
		return this.text.toLocaleUpperCase();
	}

}

// Demonstration:
let obj = new Immutable('Demo');
let json = Serialize(obj, Immutable);
let obj2 = Deserialize(json, Immutable, false);

console.log(obj.getUppercaseText());  // DEMO
console.log(obj2.getUppercaseText()); // TypeError: obj2.getUppercaseText is not a function
```

## Edit
I had some spare time, so I made a pull request (#80) to resolve this.

**Comment by TheBinaryFox** [comment]
PR #80 is merged.

This is now fixed in version 2.
