### ISSUE TITLE
Is ist possible to cerialize a Map

### ISSUE THREAD

**Issue by johanlantz** [weichx/cerialize#86]
Hi and thanks for the awesome project. Got me started in no time.

I just have one thing that I could not get right so far. 

I have a Map object looking like this
Map<string, UserInfo>

but I am not able to serialize it. I have tried a few combinations of autoserializeAs and autoserializeIndexable but I can not get it to work. 

Should this be possible? If so, a quick hint on how to decorate things would be very much appreciated.

Thanks again for the great work

**Comment by weichx** [comment]
For an actual Map instance I don't think its supported but you can use an indexable object. if you need that transformation you can write a custom Serializer for it to pump the data into an actual map instance instead of just an object.

**Comment by weichx** [comment]
I think version 2 supports that but I haven't officially released it yet

**Comment by johanlantz** [comment]
I saw the indexable object example. Will give it a try, thanks a lot for the quick answer.
