### ISSUE TITLE
Deserializing can circumvent primitive types

### ISSUE THREAD

**Issue by pkruithof** [weichx/cerialize#94]
Given this class:

```typescript
class Foo {
  @autoserialize num: number;
}
```

Deserializing a payload with a different type leads to the wrong type:

```typescript
console.log(
  Deserialize({"num": "1"}, Foo)
);
// Foo { num: '1' }
```

This is also the case the other way around (if you pass a number for a string property, it remains a number). This way you don't have type safety.

Am I doing it wrong here, or is this expected behaviour?

**Comment by prudnikov** [comment]
Just tried it with v2 and it works as expected

```
class Foo {
  @autoserializeAs(Number) num: number;
}
console.log(Deserialize({"num": "1"}, Foo));
// Foo {num: 1}
```

**Comment by pkruithof** [comment]
So number should always be explicitly typed? Can it not be inferred from the defined type? Is this also the case for strings and other primitive types?

**Comment by prudnikov** [comment]
I believe it is due to different instantiation methods added in v2 which may require calling a constructor, but not sure. Here `Number` is a constructor for the number type. I have no problem with this syntax and successfully use v2 on production.
